steps:
  # Build the JAR file using Maven
  - name: 'maven:3.8.4-openjdk-21'
    entrypoint: mvn
    args: ['clean', 'package', '-DskipTests']

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-assistant-backend', '.']

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-assistant-backend']

images:
  - 'gcr.io/$PROJECT_ID/ai-assistant-backend'